### ISSUE TITLE
Update workshopper-adventure to v4.2.x

### ISSUE THREAD

**Issue by claudiopro** [claudiopro/learn-sass#28]
See [issue #16](https://github.com/workshopper/workshopper-adventure/issues/16) for more details on `workshopper-adventure` interface changes.

**Comment by claudiopro** [comment]
Essentially, this:

```js
workshopper({
    name        : 'learn-sass'
  , title       : 'Learn SASS'
  , exerciseDir : path.join(__dirname, 'exercises')
  , appDir      : __dirname
  , languages   : ['en', 'it', 'pt-br']
})
```

turns to:

```js
workshopper({
    name        : 'learn-sass'
  , title       : 'Learn SASS'
  , exerciseDir : path.join(__dirname, 'exercises')
  , appDir      : __dirname
  , languages   : ['en', 'it', 'pt-br']
}).execute()
```

**Comment by claudiopro** [comment]
Further changes:

- Switch to binary executable under `bin/` (see `learnyounode`)
- Use `workshopper-adventure-test` to run tests
- Integrate with Travis CI

**Comment by martinheidegger** [comment]
Also: you can remove the name from the specification object (it will be automatically loaded from the package.json)

**Comment by claudiopro** [comment]
Cool, will do.

**Comment by claudiopro** [comment]
Done with #29.
