### ISSUE TITLE
Co-Maintainer?

### ISSUE THREAD

**Issue by martinheidegger** [claudiopro/learn-sass#36]
Hello @claudiopro 

learn-sass is nice but it seems you havn't had much time to update it. Would you like me to become a co-maintainer that helps keeping it up-to-date?

**Comment by claudiopro** [comment]
That would be awesome, thank you!
I'll add you now.
Regards,

**Comment by martinheidegger** [comment]
@claudiopro Would it be okay to give me npm publish permissions?
